spring:
  main:
    allow-bean-definition-overriding: true

  logging:
    level:
      org:
        keycloak: TRACE
        apache.catalina.realm: TRACE

  security:
    oauth2:
      client:
        registration:
          pierretappeti:
            provider: pierretappeti
            client-id: ${EVENDILO_PIERRETAPPETI_OAUTH_CLIENT}
            client-secret: ${EVENDILO_PIERRETAPPETI_OAUTH_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${EVENDILO_ORIGIN}/login/oauth2/code/pierretappeti
        provider:
          pierretappeti:
            authorization-uri: ${EVENDILO_PIERRETAPPETI_URL}/oauth/authorize/
            token-uri: ${EVENDILO_PIERRETAPPETI_URL}/oauth/token/
            user-info-uri: ${EVENDILO_PIERRETAPPETI_URL}/oauth/me/
            user-info-authentication-method: basic
            user-name-attribute: user_login


variables:
  corsAllowedOrigin: ${EVENDILO_CORS_ALLOWED_ORIGIN}
  woocommerce:
    - identifier: "pierretappeti"
      url: ${EVENDILO_PIERRETAPPETI_URL}
      importerConfig:
        attributes: ${EVENDILO_PIERRETAPPETI_IMPORTER_ATTRIBUTES}
      credentials:
        username: ${EVENDILO_PIERRETAPPETI_API_USERNAME}
        password: ${EVENDILO_PIERRETAPPETI_API_PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG
#      apache:
#        http: DEBUG
#      httpclient:
#        wire: DEBUG